// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drwzvrydugqhorqspnau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyd3p2cnlkdWdxaG9ycXNwbmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDExNTQsImV4cCI6MjA2NjMxNzE1NH0.hwWG7-Sh6qxk2XjLRjcquMp-8YDF7IBvkTNq8ZeQ5Rk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);